### ISSUE TITLE
Can't run bufferkdtree example after installation

### ISSUE THREAD

**Issue by liujianqiao** [gieseke/bufferkdtree#3]
Hi, Fabian,

I'm trying to run the bufferkdtree code following the document. I install the bufferkdtree with the command "**python setup.py install --user**" and the last few lines of output are:

_Writing /home/min/a/liu1274/.local/lib/python2.7/site-packages/neighbors_brute-0.0.0-py2.7.egg-info
running install_clib
customize UnixCCompiler_

Since there is no obvious signal to show whether the installation succeeds or fails, so I assume it's good and continue with the example in the document. However, when I execute the "**nbrs_buffer_kd_tree.fit(X)**", it doesn't work well:

_Traceback (most recent call last):
  File "test.py", line 16, in <module>
    nbrs_buffer_kd_tree.fit(X)
  File "/home/min/a/liu1274/workspace/bufferkdtree-master/bufferkdtree/neighbors/base.py", line 194, in fit
    self.wrapper = self._get_wrapper()
  File "/home/min/a/liu1274/workspace/bufferkdtree-master/bufferkdtree/neighbors/base.py", line 295, in _get_wrapper
    from bufferkdtree.neighbors.brute.base import BruteNN
  File "/home/min/a/liu1274/workspace/bufferkdtree-master/bufferkdtree/neighbors/brute/base.py", line 12, in <module>
    import bufferkdtree.neighbors.brute.wrapper_cpu_float as wrapper_cpu_float
ImportError: No module named wrapper_cpu_float_

I was wondering whether I installed the bufferkdtree correctly and how to figure this problem out. I'm using a university server, so I can't have the root access. 

Thanks very much!

Jianqiao

**Comment by gieseke** [comment]
Hi Jianqiao,

it seems that the shared objects are not compiled correctly (the import error in the last line indicates that). You can check that via 
`cd ~/.local/lib/python2.7/site-packages/bufferkdtree/neighbors/brute`
`ls`

You should get something like

`...`
`-rw-rw-r-- 1 fgieseke fgieseke   8580 Nov  4 18:12 wrapper_cpu_float.py`
`-rw-rw-r-- 1 fgieseke fgieseke  10809 Nov  4 18:13 wrapper_cpu_float.pyc`
`-rwxrwxr-x 1 fgieseke fgieseke 475448 Nov  4 18:13 _wrapper_cpu_float.so`
`...`

If not, then the installation/compilation was not successful...

The last lines of the installation process look basically the same on my machine. Are there any errors messages above these lines?

Best,
Fabian

**Comment by liujianqiao** [comment]
Thanks very much for the quick response!

I do get the files like yours:

_-bash-4.1$ pwd
/home/min/a/liu1274/.local/lib/python2.7/site-packages/bufferkdtree/neighbors/brute
-bash-4.1$ ll
total 1.4M
-rw-r--r-- 1 liu1274  14K Jul 27 10:28 base.py
-rw-r--r-- 1 liu1274  13K Oct 31 18:58 base.pyc
-rw-r--r-- 1 liu1274   55 Jul 27 10:28 __init__.py
-rw-r--r-- 1 liu1274  253 Oct 31 18:58 **init**.pyc
-rw-r--r-- 1 liu1274 4.8K Jul 27 10:28 setup.py
-rw-r--r-- 1 liu1274 3.2K Oct 31 18:58 setup.pyc
-rw-r--r-- 1 liu1274 8.5K Nov  4 01:28 wrapper_cpu_double.py
-rw-r--r-- 1 liu1274  11K Nov  4 01:32 wrapper_cpu_double.pyc
-rwxr-xr-x 1 liu1274 293K Nov  4 01:29 _wrapper_cpu_double.so
-rw-r--r-- 1 liu1274 8.4K Nov  4 01:28 wrapper_cpu_float.py
-rw-r--r-- 1 liu1274  11K Nov  4 01:32 wrapper_cpu_float.pyc
-rwxr-xr-x 1 liu1274 293K Nov  4 01:29 _wrapper_cpu_float.so
-rw-r--r-- 1 liu1274 9.0K Nov  4 01:28 wrapper_gpu_opencl_double.py
-rw-r--r-- 1 liu1274  11K Nov  4 01:32 wrapper_gpu_opencl_double.pyc
-rwxr-xr-x 1 liu1274 293K Nov  4 01:29 _wrapper_gpu_opencl_double.so
-rw-r--r-- 1 liu1274 9.0K Nov  4 01:28 wrapper_gpu_opencl_float.py
-rw-r--r-- 1 liu1274  11K Nov  4 01:32 wrapper_gpu_opencl_float.pyc
-rwxr-xr-x 1 liu1274 293K Nov  4 01:29 _wrapper_gpu_opencl_float.so_

To show the whole installation log, I reinstall the whole package and attach the log file here. I don't find any error though. 

_python setup.py install --user > installation.txt_
[installation.txt](https://github.com/gieseke/bufferkdtree/files/572412/installation.txt)

Jianqiao

**Comment by gieseke** [comment]
Hi Jianqiao,

sorry for the delay! I think the problem is that you are actually not using the package installed in the .local directory in your home directory, but the one given in /home/min/a/liu1274/workspace/bufferkdtree-master/ . This can happen, for instance, if you execute your run file from within the bufferkdtree-master directory (you have to move that to another place) or by your IDE using this package instead of the one installed in your home dir.

Let me know if this resolves your problem!

Best,
Fabian

**Comment by liujianqiao** [comment]
Hi, Fabian,

Thanks for the suggestion!
I executed the test script outside of /bufferkdtree-master/ folder and the output changed.

_-bash-4.1$ python test.py 
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    nbrs_buffer_kd_tree.fit(X)
  File "/home/min/a/liu1274/.local/lib/python2.7/site-packages/bufferkdtree/neighbors/base.py", line 194, in fit
    self.wrapper = self._get_wrapper()
  File "/home/min/a/liu1274/.local/lib/python2.7/site-packages/bufferkdtree/neighbors/base.py", line 297, in _get_wrapper
    from bufferkdtree.neighbors.buffer_kdtree.base import BufferKDTreeNN
  File "/home/min/a/liu1274/.local/lib/python2.7/site-packages/bufferkdtree/neighbors/buffer_kdtree/base.py", line 15, in <module>
    import bufferkdtree.neighbors.buffer_kdtree.wrapper_cpu_float as wrapper_cpu_float
  File "/home/min/a/liu1274/.local/lib/python2.7/site-packages/bufferkdtree/neighbors/buffer_kdtree/wrapper_cpu_float.py", line 28, in <module>
    _wrapper_cpu_float = swig_import_helper()
  File "/home/min/a/liu1274/.local/lib/python2.7/site-packages/bufferkdtree/neighbors/buffer_kdtree/wrapper_cpu_float.py", line 24, in swig_import_helper
    _mod = imp.load_module('_wrapper_cpu_float', fp, pathname, description)
ImportError: /home/min/a/liu1274/.local/lib/python2.7/site-packages/bufferkdtree/neighbors/buffer_kdtree/_wrapper_cpu_float.so: undefined symbol: clReleaseDevice_

It looks like my OpenCL version is too old to support the bufferkdtree. I'm trying to update the OpenCL and will let you know my progress. Thanks!

Jianqiao

**Comment by liujianqiao** [comment]
BTW, is there an OpenCL version requirement for bufferkdtree? Our server is using OpenCL 1.0 (CUDA 7.0) and this is the latest version that I can find...

Jianqiao

**Comment by gieseke** [comment]
Good point! The code requires OpenCL 1.2 (which should also be supported by the recent CUDA frameworks). I have added a corresponding note to the installation instructions of the documentation.

Did you manage to get everything running?

Cheers,
Fabian

**Comment by liujianqiao** [comment]
Finally, I got a chance to use a local desktop that I can fully control everything! After tens of times of tries, I figure out the way to run bufferkdtree. Here are what I found:
1. For local machine, the pip installation can't find the OpenCL lib correctly even with the correct "C_INCLUDE_APTH" and "LIBRARY_PATH". To overcome this, you'd better manually copy the lib file to "/usr/lib" file:
   _sudo cp /usr/local/cuda/lib64/libOpenCL.so /usr/lib
   sudo ln -s /usr/local/cuda/include/CL /usr/include_
2. For server environment, bufferkdtree doesn't work well. My latest problem is:
   _-bash-4.1$ python test.py 
   Traceback (most recent call last):
   File "test.py", line 16, in <module>
     nbrs_buffer_kd_tree.fit(X)
   File "/home/min/a/liu1274/.local/lib/python2.7/site-packages/bufferkdtree/neighbors/base.py", line 194, in fit
     self.wrapper = self._get_wrapper()
   File "/home/min/a/liu1274/.local/lib/python2.7/site-packages/bufferkdtree/neighbors/base.py", line 297, in _get_wrapper
     from bufferkdtree.neighbors.buffer_kdtree.base import BufferKDTreeNN
   File "/home/min/a/liu1274/.local/lib/python2.7/site-packages/bufferkdtree/neighbors/buffer_kdtree/base.py", line 15, in <module>
     import bufferkdtree.neighbors.buffer_kdtree.wrapper_cpu_float as wrapper_cpu_float
   File "/home/min/a/liu1274/.local/lib/python2.7/site-packages/bufferkdtree/neighbors/buffer_kdtree/wrapper_cpu_float.py", line 28, in <module>
     _wrapper_cpu_float = swig_import_helper()
   File "/home/min/a/liu1274/.local/lib/python2.7/site-packages/bufferkdtree/neighbors/buffer_kdtree/wrapper_cpu_float.py", line 24, in swig_import_helper
     _mod = imp.load_module('_wrapper_cpu_float', fp, pathname, description)
   ImportError: /home/min/a/liu1274/.local/lib/python2.7/site-packages/bufferkdtree/neighbors/buffer_kdtree/_wrapper_cpu_float.so: undefined symbol: clReleaseDevice_

I'm still working on the server version since my major work is done on servers. It looks like some OpenCL lib problem, but I'm not sure how to figure it out since I don't have root authentication.

Jianqiao

**Comment by gieseke** [comment]
Hi Jianqiao,

great that you managed to finally install the package on your laptop! Concerning the server: It seems to be an OpenCL version problem, as pointed out by you before. OpenCL >= 1.2 is needed I guess. BTW: It should be possible to install the most recent CUDA (SDK) locally in your home directory on your server (along with OpenCL >= 1.2), see http://docs.nvidia.com/cuda/cuda-installation-guide-linux .

Cheers,
Fabian
